// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfbowslvalugjmwqgzdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYm93c2x2YWx1Z2ptd3FnemRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODU4NTAsImV4cCI6MjA3MjA2MTg1MH0.winZY7RgzbEwRwDY4SRB20oj8Ix514Pu7rYPosRUQTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});